repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  # Fails if there are any ">>>>>" lines in files due to merge conflicts.
  - id: check-merge-conflict
  # Trims trailing whitespace. Allow a single space on the end of .md lines for hard line breaks.
  - id: trailing-whitespace
    args: [ --markdown-linebreak-ext=md ]
  # Makes sure files end in a newline and only a newline;
  - id: end-of-file-fixer
  # Attempts to load all TOML files to verify syntax.
  - id: check-toml
  # Attempts to load all yaml files to verify syntax; unsafe: only check syntax, do not load yaml
  - id: check-yaml
    args: [ "--unsafe" ]
  # Check for symlinks that do not point to anything.
  - id: check-symlinks
  # Fail if staged files are above a certain size.
  - id: check-added-large-files
    args: [ "--maxkb=500" ]
    exclude: |
      (?x)(
        ^example/large/file.csv|
        ^example/large/sklearn-model.pkl
      )
  # Sort requirements in requirements.txt files.
  - id: requirements-txt-fixer
  # Prevent addition of new git submodules.
  # Detects the presence of private keys
  - id: detect-private-key

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: "v1.18.2"
  hooks:
  - id: mypy
    args: [ --no-strict-optional, --ignore-missing-imports, --config-file=./pyproject.toml ]

- repo: https://github.com/psf/black
  rev: 25.9.0
  hooks:
  - id: black
    args:
    - --config=./pyproject.toml

- repo: https://github.com/PyCQA/pylint
  rev: v4.0.2
  hooks:
  - id: pylint
    args:
    - --rcfile=./pyproject.toml

- repo: https://github.com/pycqa/isort
  rev: 7.0.0
  hooks:
  - id: isort
    args:
    - --settings-path=./pyproject.toml
